import json
import os
import re
from pathlib import Path
from typing import Dict, Any, List
import logging

# 全出力対象キー（英語→日本語マップ付き）
KEYS = [
    ("FAX番号", "FAX番号"),
    ("URL", "物件詳細URL"),
    ("address", "住所"),
    ("address.latitude", "緯度"),
    ("address.longitude", "経度"),
    ("address.text", "住所（テキスト）"),
    ("advertisement_reprint_available_type", "広告転載可否"),
    ("all_images", "画像一覧"),
    ("all_images.type", "all_images.type"),
    ("all_images.url", "all_images.url"),
    ("all_options", "設備一覧"),
    ("all_options.text", "all_options.text"),
    ("all_options.value", "all_options.value"),
    ("balcony_text", "バルコニー"),
    ("bicycle_parking_chinryo_text", "駐輪場料金"),
    ("booked_category_type", "地目"),
    ("building_age_text", "築年数"),
    ("building_coverage_ratio_text", "建ぺい率"),
    ("building_detail_type", "建物種別"),
    ("building_name", "建物名"),
    ("building_number", "棟番号"),
    ("cancellation_notice_period", "解約予告期間"),
    ("car_parking", "car_parking"),
    ("car_parking.chinryo_text", "駐車場賃料"),
    ("car_parking.text", "駐車場"),
    ("city_planning_type", "都市計画"),
    ("connected_road_text", "接道"),
    ("construction", "construction"),
    ("construction.company_name", "施工会社"),
    ("construction.sale_company_name", "売主会社"),
    ("construction_date_text", "建築年月"),
    ("contract_renewal_type", "契約更新種別"),
    ("contract_terms", "契約期間"),
    ("contract_type", "契約種別"),
    ("creating_estimate_availability", "creating_estimate_availability"),
    ("creating_zumen_availability", "creating_zumen_availability"),
    ("current_annual_yield_text", "現況利回り"),
    ("current_state_type", "現況"),
    ("deal_type", "取引形態"),
    ("expected_annual_rental_income_text", "想定年間収入"),
    ("expected_annual_yield_text", "想定利回り"),
    ("floor_area_text", "専有面積"),
    ("floor_text", "所在階"),
    ("free_rent_text", "フリーレント"),
    ("full_name", "物件名"),
    ("hoshokin_text", "保証金"),
    ("hoshoryo", "hoshoryo"),
    ("hoshoryo.remarks", "保証料備考"),
    ("hoshoryo.text", "保証料"),
    ("images", "画像一覧（詳細）"),
    ("images.alt", "images.alt"),
    ("images.filename", "images.filename"),
    ("images.index", "images.index"),
    ("images.local_path", "images.local_path"),
    ("images.url", "images.url"),
    ("images.ファイル名", "images.ファイル名"),
    ("images.番号", "images.番号"),
    ("insurance_text", "保険料"),
    ("is_bukkaku_necessary", "物確要否"),
    ("kanrihi_text", "管理費"),
    ("kenrikin_text", "権利金"),
    ("key_unlock_way_detail", "鍵の受け渡し方法"),
    ("kokokuhi_text", "広告費"),
    ("koshinryo_text", "更新料"),
    ("kyoekihi_text", "kyoekihi_text"),
    ("land_area_text", "土地面積"),
    ("land_deal", "land_deal"),
    ("land_deal.kokudoho_report_type", "国土法届出"),
    ("land_deal.ownership_transfer_type", "所有権移転"),
    ("land_deal.right_type", "権利種別"),
    ("land_floor_area_ratio_text", "容積率"),
    ("land_rent", "地代"),
    ("land_share_text", "土地共有持分"),
    ("latitude", "latitude"),
    ("layout", "間取り"),
    ("layout.spaces", "layout.spaces"),
    ("layout.text", "間取り（テキスト）"),
    ("layout_text", "layout_text"),
    ("legal_restriction_remarks", "legal_restriction_remarks"),
    ("longitude", "longitude"),
    ("main_lighting_direction_type", "主要採光面"),
    ("management", "management"),
    ("management.association_type", "管理組合"),
    ("management.form_type", "管理形態"),
    ("management.method_type", "管理方式"),
    ("management_company", "management_company"),
    ("management_company.contact_url", "管理会社URL"),
    ("management_company.name", "管理会社名"),
    ("management_company.phone_number", "管理会社電話番号"),
    ("motorbike_parking_chinryo_text", "バイク置場料金"),
    ("nearby_places_text", "周辺施設"),
    ("nearby_train_station_texts", "最寄り駅情報"),
    ("offer_zumens_count", "図面数"),
    ("optimal_usage_type", "最適用途"),
    ("other_costs", "その他費用"),
    ("other_costs.period_costs", "other_costs.period_costs"),
    ("other_costs.type", "other_costs.type"),
    ("pet_negotiation", "pet_negotiation"),
    (
        "pet_negotiation.pet_availabilities",
        "pet_negotiation.pet_availabilities",
    ),
    (
        "pet_negotiation.pet_available_type",
        "pet_negotiation.pet_available_type",
    ),
    ("pet_negotiation.remarks", "ペット備考"),
    ("price", "price"),
    ("price_per_tsubo_text", "坪単価"),
    ("price_text", "価格"),
    ("private_contribution_text", "私道負担"),
    ("property_id", "物件ID"),
    ("property_transfer_period_text", "引渡時期"),
    ("reikin_text", "礼金"),
    ("remarks", "備考"),
    ("rent_text", "賃料"),
    ("room_number", "部屋番号"),
    ("room_property_id", "部屋物件ID"),
    ("rooms_total_count", "部屋数"),
    ("seller_chukairyo_text", "seller_chukairyo_text"),
    ("setback_text", "セットバック"),
    ("shikibiki_shokyaku_text", "敷引・償却"),
    ("shikikin_text", "敷金"),
    ("shikikin_tsumimashi_text", "敷金積増し"),
    ("site_area_text", "敷地面積"),
    ("site_extension_text", "接道間口"),
    ("status", "status"),
    ("status_remarks", "ステータス備考"),
    ("status_type", "ステータス"),
    ("story_text", "階建"),
    ("structure_type", "構造"),
    ("total_floor_area_text", "延床面積"),
    ("total_units", "total_units"),
    ("tsumitatekin_text", "修繕積立金"),
    ("viewing_available_from", "内見可能日"),
    ("viewing_note", "内見備考"),
    ("vr_image_url", "VR画像URL"),
    ("water_charge_type", "water_charge_type"),
    ("yoto_chiiki_types", "yoto_chiiki_types"),
    ("その他交通", "その他交通"),
    ("その他月額費名称", "その他月額費名称"),
    ("その他月額費金額", "その他月額費金額"),
    ("その他費用", "その他費用"),
    ("その他費用月額", "その他費用月額"),
    ("アクセス", "アクセス"),
    ("アクセス.徒歩", "アクセス.徒歩"),
    ("アクセス.番号", "アクセス.番号"),
    ("アクセス.駅名", "アクセス.駅名"),
    ("エレベータ", "エレベータ"),
    ("オススメ情報", "オススメ情報"),
    ("キッチン/バス・トイレ", "キッチン/バス・トイレ"),
    ("スクレイピング日時", "スクレイピング日時"),
    ("ステータス", "ステータス"),
    ("セキュリティ/サービス/条件", "セキュリティ/サービス/条件"),
    ("セールスポイント", "セールスポイント"),
    ("テラス面積", "テラス面積"),
    ("バス停", "バス停"),
    ("バス停 徒歩", "バス停 徒歩"),
    ("バルコニー(テラス)面積", "バルコニー(テラス)面積"),
    ("バルコニー方向", "バルコニー方向"),
    ("バルコニー面積", "バルコニー面積"),
    ("フラット３５", "フラット３５"),
    ("ペット", "ペット"),
    ("ポイント", "ポイント"),
    ("メッセージ", "メッセージ"),
    ("リフォーム", "リフォーム"),
    ("ルーフバルコニー面積", "ルーフバルコニー面積"),
    ("㎡単価", "㎡単価"),
    ("事務所使用", "事務所使用"),
    ("交通", "交通"),
    ("交通.徒歩時間", "交通.徒歩時間"),
    ("交通.路線名", "交通.路線名"),
    ("交通.駅名", "交通.駅名"),
    ("付記", "付記"),
    ("代表電話番号", "代表電話番号"),
    ("仲介手数料/分配率", "仲介手数料/分配率"),
    ("住所", "住所"),
    ("使用部分面積", "使用部分面積"),
    ("価格", "価格"),
    ("保証金", "保証金"),
    ("修繕積立基金", "修繕積立基金"),
    ("修繕積立金", "修繕積立金"),
    ("修繕積立金月額", "修繕積立金月額"),
    ("備考", "備考"),
    ("免許番号", "免許番号"),
    ("入居可能時期", "入居可能時期"),
    ("共益費", "共益費"),
    ("内装", "内装"),
    ("内装/家具・家電/通信", "内装/家具・家電/通信"),
    ("分譲会社名", "分譲会社名"),
    ("取引態様", "取引態様"),
    ("取引状況", "取引状況"),
    ("取引状況の補足", "取引状況の補足"),
    ("取扱会社", "取扱会社"),
    ("向き", "向き"),
    ("商号", "商号"),
    ("問い合わせ担当者", "問い合わせ担当者"),
    ("問い合わせ電話番号", "問い合わせ電話番号"),
    ("固都税年額", "固都税年額"),
    ("国土法届出", "国土法届出"),
    ("土地", "土地"),
    ("土地権利", "土地権利"),
    ("土地面積", "土地面積"),
    ("地上階層", "地上階層"),
    ("地下階層", "地下階層"),
    ("坪単価", "坪単価"),
    ("基本設備・条件", "基本設備・条件"),
    ("報酬形態", "報酬形態"),
    ("変更年月日", "変更年月日"),
    ("契約期間", "契約期間"),
    ("客付会社様へのメッセージ", "客付会社様へのメッセージ"),
    ("容積率", "容積率"),
    ("専有面積", "専有面積"),
    ("専用庭面積", "専用庭面積"),
    ("広告転載区分", "広告転載区分"),
    ("建ぺい率", "建ぺい率"),
    ("建物", "建物"),
    ("建物名", "建物名"),
    ("建物名・号室", "建物名・号室"),
    ("建物構造", "建物構造"),
    ("建物賃貸借区分", "建物賃貸借区分"),
    ("建物面積", "建物面積"),
    ("建築年月", "建築年月"),
    ("建築確認番号", "建築確認番号"),
    ("引渡日", "引渡日"),
    ("引渡時期", "引渡時期"),
    ("所在地", "所在地"),
    ("所在地名１", "所在地名１"),
    ("所在地名２", "所在地名２"),
    ("所在階", "所在階"),
    ("手数料割合率", "手数料割合率"),
    ("担当社員所属部署", "担当社員所属部署"),
    ("接道状況", "接道状況"),
    ("敷金", "敷金"),
    ("新築中古区分", "新築中古区分"),
    ("施工", "施工"),
    ("施工会社名", "施工会社名"),
    ("更新年月日", "更新年月日"),
    ("更新料", "更新料"),
    ("更新日", "更新日"),
    ("最寄り駅", "最寄り駅"),
    ("最寄り駅 徒歩", "最寄り駅 徒歩"),
    ("棟総戸数", "棟総戸数"),
    ("構造・所在階", "構造・所在階"),
    ("権利金", "権利金"),
    ("満室想定月額賃料", "満室想定月額賃料"),
    ("物件ID", "物件ID"),
    ("物件名", "物件名"),
    ("物件名・部屋番号", "物件名・部屋番号"),
    ("物件情報", "物件情報"),
    ("物件情報.URL", "物件情報.URL"),
    ("物件情報.バルコニー面積", "物件情報.バルコニー面積"),
    ("物件情報.交通", "物件情報.交通"),
    ("物件情報.価格", "物件情報.価格"),
    ("物件情報.修繕積立金", "物件情報.修繕積立金"),
    ("物件情報.備考", "物件情報.備考"),
    ("物件情報.取引態様", "物件情報.取引態様"),
    ("物件情報.専有面積", "物件情報.専有面積"),
    ("物件情報.所在地", "物件情報.所在地"),
    ("物件情報.新着", "物件情報.新着"),
    ("物件情報.構造", "物件情報.構造"),
    ("物件情報.物件ID", "物件情報.物件ID"),
    ("物件情報.物件名", "物件情報.物件名"),
    ("物件情報.物件名_詳細", "物件情報.物件名_詳細"),
    ("物件情報.物件紹介", "物件情報.物件紹介"),
    ("物件情報.画像", "物件情報.画像"),
    ("物件情報.画像.URL", "物件情報.画像.URL"),
    ("物件情報.画像.インデックス", "物件情報.画像.インデックス"),
    ("物件情報.画像.ファイル名", "物件情報.画像.ファイル名"),
    ("物件情報.画像.保存パス", "物件情報.画像.保存パス"),
    ("物件情報.画像.種類", "物件情報.画像.種類"),
    ("物件情報.管理形態", "物件情報.管理形態"),
    ("物件情報.管理費", "物件情報.管理費"),
    ("物件情報.築年月", "物件情報.築年月"),
    ("物件情報.販売価格", "物件情報.販売価格"),
    ("物件情報.間取り", "物件情報.間取り"),
    ("物件情報.階建 / 所在階", "物件情報.階建 / 所在階"),
    ("物件番号", "物件番号"),
    ("物件種別", "物件種別"),
    ("物件種目", "物件種目"),
    ("現況", "現況"),
    ("用途地域", "用途地域"),
    ("用途地域1", "用途地域1"),
    ("用途地域2", "用途地域2"),
    ("画像", "画像"),
    ("画像.alt", "画像.alt"),
    ("画像.caption", "画像.caption"),
    ("画像.file_name", "画像.file_name"),
    ("画像.filename", "画像.filename"),
    ("画像.index", "画像.index"),
    ("画像.original_url", "画像.original_url"),
    ("画像.saved_path", "画像.saved_path"),
    ("画像.type", "画像.type"),
    ("画像.url", "画像.url"),
    ("登録年月日", "登録年月日"),
    ("目安光熱費", "目安光熱費"),
    ("礼金", "礼金"),
    ("立地条件/土地", "立地条件/土地"),
    ("管理人", "管理人"),
    ("管理人状況", "管理人状況"),
    ("管理会社", "管理会社"),
    ("管理会社名", "管理会社名"),
    ("管理形態", "管理形態"),
    ("管理番号", "管理番号"),
    ("管理組合", "管理組合"),
    ("管理組合有無", "管理組合有無"),
    ("管理費", "管理費"),
    ("管理費月額", "管理費月額"),
    ("築年", "築年"),
    ("築年数", "築年数"),
    ("築年月", "築年月"),
    ("経度", "経度"),
    ("総戸(室)数", "総戸(室)数"),
    ("総戸数", "総戸数"),
    ("緯度", "緯度"),
    ("耐震", "耐震"),
    ("自社管理欄", "自社管理欄"),
    ("補足", "補足"),
    ("設備/構造/リフォーム", "設備/構造/リフォーム"),
    ("設備・条件・住宅性能等", "設備・条件・住宅性能等"),
    ("販売会社", "販売会社"),
    ("販売価格", "販売価格"),
    ("賃料", "賃料"),
    ("部屋数・間取り", "部屋数・間取り"),
    ("部屋番号", "部屋番号"),
    ("都市計画", "都市計画"),
    ("都道府県名", "都道府県名"),
    ("金額", "金額"),
    ("間取り", "間取り"),
    ("間取タイプ", "間取タイプ"),
    ("間取部屋数", "間取部屋数"),
    ("階建", "階建"),
    ("階数", "階数"),
    ("電話番号", "電話番号"),
    ("面積", "面積"),
    ("面積計測方式", "面積計測方式"),
    ("駐車場", "駐車場"),
    ("駐車場・駐輪場/庭", "駐車場・駐輪場/庭"),
    ("駐車場在否", "駐車場在否"),
    ("駐車場月額", "駐車場月額"),
    ("駐車場月額(最低値)", "駐車場月額(最低値)"),
    ("駐車場月額(最高値)", "駐車場月額(最高値)"),
    ("駐車場（月額）", "駐車場（月額）"),
    ("駐輪場", "駐輪場"),
    ("building_name", "物件名"),
    ("rent_text", "賃料"),
    ("reikin_text", "礼金"),
    ("shikikin_text", "敷金"),
    ("hoshokin_text", "保証金"),
    ("kanrihi_text", "管理費"),
    ("nearby_train_station_texts", "交通"),
    ("floor_area_text", "面積"),


]

# 金額変換対象キー（英語）
PRICE_KEYS = {
    "price_text",
    "rent_text",
    "reikin_text",
    "shikikin_text",
    "kanrihi_text",
    "price_per_tsubo_text",
    "expected_annual_rental_income_text",
    "expected_annual_yield_text",
    "current_annual_yield_text",
}


# 金額表現を数値に変換
def parse_japanese_price(text):
    if not isinstance(text, str):
        return text
    text = (
        text.replace(",", "")
        .replace(" ", "")
        .replace("（税込）", "")
        .replace("税込", "")
    )
    match = re.match(r"(?:(\d+)億)?(?:(\d+)万)?円?", text)
    if not match:
        try:
            return int(re.sub(r"[^\d]", "", text))
        except:
            return text
    oku = int(match.group(1)) if match.group(1) else 0
    man = int(match.group(2)) if match.group(2) else 0
    return oku * 100_000_000 + man * 10_000


# 辞書を flatten（ドット記法に変換）
def flatten_dict(d, parent_key="", sep="."):
    items = {}
    for k, v in d.items():
        new_key = f"{parent_key}{sep}{k}" if parent_key else k
        if isinstance(v, dict):
            items.update(flatten_dict(v, new_key, sep=sep))
        else:
            items[new_key] = v
    return items


# 翻訳処理（すべてのキーを網羅し、存在しないキーは null）
def translate_json(data):
    flat = flatten_dict(data)
    out = {}
    for en_key, jp_key in KEYS:
        val = flat.get(en_key, None)
        if en_key in PRICE_KEYS:
            out[jp_key] = parse_japanese_price(val) if val is not None else None
        else:
            out[jp_key] = val
    return out


class JsonMerger:
    def __init__(self):
        self.logger = logging.getLogger(__name__)
        self.data_dir = "data"
        self.merged_file = "merged.json"
        
        # 別名マッピング
        self.key_mappings = {
            "物件ID": ["property_id", "物件番号", "物件ID"],
            "物件名": ["物件名", "物件名・部屋番号", "建物名・号室", "建物名"],
            "価格": ["価格", "金額", "販売価格", "賃料"],
            "所在地": ["所在地", "住所", "所在地名", "所在地名１"],
            "築年月": ["築年月", "築年", "築年数", "築年月日"],
            "専有面積": ["専有面積", "面積", "使用部分面積"],
            "間取り": ["間取り", "部屋数・間取り", "layout", "layout_text"],
            "管理費": ["管理費", "管理費月額", "共益費", "共益費月額"],
            "修繕積立金": ["修繕積立金", "修繕積立金月額", "修繕費", "修繕費月額"],
            "駐車場": ["駐車場", "駐車場（月額）", "駐車場月額", "駐車場料金"],
            "最寄り駅": ["最寄り駅", "交通", "アクセス", "nearby_train_station_texts"],
            "最寄り駅 徒歩": ["最寄り駅 徒歩", "交通.徒歩時間", "アクセス.徒歩"],
            "バルコニー": ["バルコニー", "バルコニー面積", "テラス", "テラス面積"],
            "階建": ["階建", "階数", "構造・所在階", "階層"],
            "用途地域": ["用途地域", "用途", "用途地域1", "用途地域2"],
            "総戸数": ["総戸数", "総戸(室)数", "総戸室数", "total_units"],
            "その他費用": ["その他費用", "その他費用月額", "その他料金", "other_costs"],
            "備考": ["備考", "remarks", "物件情報.備考", "物件紹介"],
            "画像": ["画像", "all_images", "物件情報.画像", "images"],
            "建物構造": ["建物構造", "構造", "structure_type", "物件情報.構造"],
            "管理形態": ["管理形態", "management.form_type", "物件情報.管理形態"],
            "現況": ["現況", "current_state_type", "status_type", "ステータス"],
            "引渡時期": ["引渡時期", "property_transfer_period_text", "入居可能時期"],
            "敷金": ["敷金", "shikikin_text", "保証金", "hoshokin_text"],
            "礼金": ["礼金", "reikin_text", "権利金", "kenrikin_text"],
            "更新料": ["更新料", "koshinryo_text", "更新手数料"],
            "管理会社名": ["管理会社名", "management_company.name", "管理会社", "分譲会社名"],
            "施工会社名": ["施工会社名", "construction.company_name", "施工会社", "施工"],
            "都道府県名": ["都道府県名", "address.prefecture", "所在地名１"],
            "容積率": ["容積率", "land_floor_area_ratio_text", "建ぺい率", "building_coverage_ratio_text"],
            "用途": ["用途", "optimal_usage_type", "用途地域", "用途地域1"],
            "設備": ["設備", "all_options", "設備/構造/リフォーム", "設備・条件・住宅性能等"],
            "内装": ["内装", "内装/家具・家電/通信", "キッチン/バス・トイレ"],
            "交通": ["交通", "アクセス", "最寄り駅", "nearby_train_station_texts"],
            "向き": ["向き", "main_lighting_direction_type", "バルコニー方向"],
            "契約期間": ["契約期間", "contract_terms", "契約種別", "contract_type"],
            "管理組合": ["管理組合", "management.association_type", "管理組合有無"],
            "管理人": ["管理人", "management_company.method_type", "management.method_type"],
            "駐輪場": ["駐輪場", "bicycle_parking_chinryo_text", "駐車場・駐輪場/庭"],
            "その他交通": ["その他交通", "バス停", "バス停 徒歩"],
            "専用庭面積": ["専用庭面積", "ルーフバルコニー面積", "テラス面積"],
            "地下階層": ["地下階層", "地上階層", "階層"],
            "事務所使用": ["事務所使用", "事務所使用可", "用途地域"],
            "分譲会社名": ["分譲会社名", "construction.sale_company_name", "管理会社名"],
            "建物名": ["建物名", "building_name", "物件名", "物件名・部屋番号"],
            "部屋番号": ["部屋番号", "room_number", "物件名・部屋番号"],
            "建物種別": ["建物種別", "building_detail_type", "物件種別"],
            "土地面積": ["土地面積", "land_area_text", "敷地面積", "site_area_text"],
            "土地権利": ["土地権利", "land_deal.right_type", "土地"],
            "都市計画": ["都市計画", "city_planning_type", "用途地域"],
            "接道": ["接道", "connected_road_text", "接道状況", "site_extension_text"],
            "セットバック": ["セットバック", "setback_text", "私道負担", "private_contribution_text"],
            "国土法届出": ["国土法届出", "land_deal.kokudoho_report_type", "国土法"],
            "所有権移転": ["所有権移転", "land_deal.ownership_transfer_type", "土地権利"],
            "ペット": ["ペット", "pet_negotiation", "ペット可"],
            "内見": ["内見", "viewing_available_from", "内見可能日", "viewing_note"],
            "保険": ["保険", "insurance_text", "保険料"],
            "鍵": ["鍵", "key_unlock_way_detail", "鍵の受け渡し方法"],
            "広告": ["広告", "advertisement_reprint_available_type", "広告転載可否", "kokokuhi_text"],
            "図面": ["図面", "offer_zumens_count", "図面数", "creating_zumen_availability"],
            "VR": ["VR", "vr_image_url", "VR画像"],
            "見積": ["見積", "creating_estimate_availability", "見積可能"],
            "取引形態": ["取引形態", "deal_type", "取引態様"],
            "取引状況": ["取引状況", "status", "ステータス", "status_type"],
            "取引状況の補足": ["取引状況の補足", "status_remarks", "ステータス備考"],
            "取扱会社": ["取扱会社", "販売会社", "management_company"],
            "問い合わせ": ["問い合わせ", "management_company.contact_url", "問い合わせ電話番号", "問い合わせ担当者"],
            "担当者": ["担当者", "担当社員所属部署", "問い合わせ担当者"],
            "電話番号": ["電話番号", "management_company.phone_number", "代表電話番号", "問い合わせ電話番号"],
            "FAX番号": ["FAX番号", "management_company.fax_number"],
            "URL": ["URL", "物件詳細URL", "management_company.contact_url"],
            "スクレイピング日時": ["スクレイピング日時", "更新日", "更新年月日", "変更年月日"],
            "登録年月日": ["登録年月日", "登録日", "created_at"],
            "更新年月日": ["更新年月日", "更新日", "変更年月日", "updated_at"],
            "免許番号": ["免許番号", "管理番号", "license_number"],
            "商号": ["商号", "company_name", "management_company.name"],
            "報酬形態": ["報酬形態", "仲介手数料/分配率", "手数料割合率"],
            "客付会社様へのメッセージ": ["客付会社様へのメッセージ", "メッセージ", "message"],
            "セールスポイント": ["セールスポイント", "ポイント", "selling_points"],
            "オススメ情報": ["オススメ情報", "recommended_info", "recommendations"],
            "付記": ["付記", "補足", "remarks"],
            "自社管理欄": ["自社管理欄", "自社管理", "self_management"],
            "基本設備・条件": ["基本設備・条件", "設備・条件・住宅性能等", "basic_facilities"],
            "耐震": ["耐震", "seismic", "seismic_performance"],
            "フラット３５": ["フラット３５", "flat35", "flat_35"],
            "目安光熱費": ["目安光熱費", "utility_costs", "estimated_utility_costs"],
            "満室想定月額賃料": ["満室想定月額賃料", "expected_monthly_rent", "full_occupancy_rent"],
            "坪単価": ["坪単価", "price_per_tsubo_text", "tsubo_price"],
            "㎡単価": ["㎡単価", "price_per_sqm_text", "sqm_price"],
            "現況利回り": ["現況利回り", "current_annual_yield_text", "current_yield"],
            "想定利回り": ["想定利回り", "expected_annual_yield_text", "expected_yield"],
            "想定年間収入": ["想定年間収入", "expected_annual_rental_income_text", "expected_annual_income"],
            "フリーレント": ["フリーレント", "free_rent_text", "free_rent_period"],
            "敷引・償却": ["敷引・償却", "shikibiki_shokyaku_text", "deposit_deduction"],
            "敷金積増し": ["敷金積増し", "shikikin_tsumimashi_text", "deposit_increase"],
            "保証料": ["保証料", "hoshoryo.text", "guarantee_fee"],
            "保証料備考": ["保証料備考", "hoshoryo.remarks", "guarantee_fee_remarks"],
            "広告費": ["広告費", "kokokuhi_text", "advertisement_fee"],
            "仲介手数料": ["仲介手数料", "brokerage_fee", "commission"],
            "分配率": ["分配率", "distribution_rate", "split_rate"],
            "手数料割合率": ["手数料割合率", "commission_rate", "fee_rate"],
            "報酬形態": ["報酬形態", "reward_type", "compensation_type"],
            "客付会社": ["客付会社", "client_company", "introducing_company"],
            "セールスポイント": ["セールスポイント", "selling_points", "key_features"],
            "オススメ情報": ["オススメ情報", "recommendations", "recommended_info"],
        }

def main():
    current_dir = os.path.dirname(os.path.abspath(__file__))
    data_dir = os.path.join(os.path.dirname(current_dir), "data")
    
    updated_list_path = Path(os.path.join(data_dir, "updated.json"))
    output_path = Path(os.path.join(data_dir, "merged.json"))

    if not updated_list_path.exists():
        print("更新物件情報ファイルが存在しません")
        return

    with open(updated_list_path, "r", encoding="utf-8") as f:
        file_list = json.load(f)

    translated_data = []
    for path in file_list:
        filepath = Path(path.replace("\\", "/"))
        if not filepath.exists():
            translated_data.append(
                {"ファイル名": str(filepath), "エラー": "ファイルが存在しません"}
            )
            continue
        with open(filepath, "r", encoding="utf-8") as f:
            raw = json.load(f)
            translated = translate_json(raw)
        translated["ファイルパス"] = str(filepath.resolve())
        translated_data.append(translated)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(translated_data, f, ensure_ascii=False, indent=2)

    print("✅ 翻訳と金額変換が完了:", output_path)


if __name__ == "__main__":
    main()
